apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.7.10-data-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: influxdb-storage
      volumes:
        - name: influxdb-storage
          nfs:
            path: /opt/nfs/influxdb
            server: 10.0.1.4
      restartPolicy: Always
  selector:
    matchLabels:
      app: influxdb
