apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    pidfile .pid
    appendonly yes
    cluster-config-file nodes-6379.conf
    pidfile /opt/data/redis/log/redis-6379.pid
    cluster-config-file /opt/conf/redis.conf
    dir /opt/data/redis/
    cluster-node-timeout 5000
